name = "TensorTrains"
uuid = "89893e69-996d-40b1-ba32-8ff5f34c0dd5"
authors = ["stecrotti <stefano.crotti@polito.it>", "abraunst <alfredo.braunstein@polito.it"]
version = "0.12.1"

[deps]
KrylovKit = "0b1a1467-8014-51b9-945f-bf0ae24f4b77"
Lazy = "50d2b5c4-7a5e-59d5-8109-a42b560f39c0"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LogarithmicNumbers = "aa2f6b4e-9042-5d33-9679-40d3a6b85899"
MKL = "33e6dc65-8f57-5167-99aa-e5a354878fb2"
MPSKit = "bb1c41ca-d63c-52ed-829e-0820dda26502"
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
TensorCast = "02d47bb6-7ce6-556a-be16-bb1710789e2b"
TensorKit = "07d1fe3e-3e46-537d-9eac-e9e13d0d4cec"
Tullio = "bc48ee85-29a4-5162-ae0b-a64e1601d4bc"

[compat]
KrylovKit = "0.6, 0.7, 0.8"
Lazy = "0.15"
LinearAlgebra = "1.8"
LogarithmicNumbers = "1.4"
MKL = "0.6.3, 0.7"
MPSKit = "0.11.5"
OffsetArrays = "1.15.0"
Optim = "1.11"
Random = "1.8"
StatsBase = "0.33, 0.34"
TensorCast = "0.4"
TensorKit = "0.12.0"
Tullio = "0.3"
julia = "1.8"
